import MovieProvider from '../app/Context/Context';  // Import your MovieProvider
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './Component/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased m-20`}>
        <Navbar/>
        <MovieProvider>  {/* Wrap your app with MovieProvider */}
          {children}   {/* This will include the Home component */}
        </MovieProvider>
      </body>
    </html>
  );
}
